version: '2.1'

services:

  rabbitmq:
#    image: rabbitmq:3.6-management
#    environment:
#      RABBITMQ_DEFAULT_USER: clickkycode
#      RABBITMQ_DEFAULT_PASS: sAfh2iqz
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    ports:
      - 15671:15671
      - 15672:15672
      - 25672:25672
      - 4369:4369
      - 5671:5671
      - 5672:5672

  nats:
    image: nats:0.9.6
    ports:
      - 8222:8222
      - 4222:4222
      - 6222:6222

  natsboard:
    image: urashidmalik/natsboard
    environment:
      NATS_MONITOR_URL: http://nats:8222
    ports:
      - 3000:3000

  nodejs:
#    image: node:8.1
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./js:/usr/src/app

  openresty:
    build:
      context: .
      dockerfile: docker/openresty/Dockerfile
    volumes:
      - ./lua:/var/www/lua
      - ./docker/openresty/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 127.0.0.1:8006:80

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock